In [ ]:
import tensorflow as tf
import cv2 as cv
import numpy as np
from Cards import getlevel
from Cards import getattribute
from Cards import getType
from matplotlib import pyplot as plt

img = cv.imread('Pictures/SampleCards/Red.jpg')

getlevel(img)

getattribute(img)

getType(img)

Status check All clear
[[[668.5  28.5  29.3]
  [566.5  27.5  27.2]
  [199.5  29.5  29.4]
  [508.5  29.5  27.1]
  [254.5  27.5  27.1]
  [615.5  28.5  29.3]
  [356.5  27.5  26.1]
  [303.5  30.5  26. ]
  [146.5  29.5  29.4]
  [406.5  28.5  28.2]
  [460.5  29.5  26.1]
  [ 96.5  28.5  26. ]]]
